title: Talent Consulting
email: contactus@talentconsulting.uk
description: >- # this means to ignore newlines until "baseurl:"
  Talent Consulting provide technical, architectural, developement and testing capabiltiy to any project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
#theme: minima
#theme: just-the-docs
#color_scheme: dark
#theme: jekyll-theme-cayman
theme: jekyll-theme-cayman
#remote_theme: benbalter/retlab
#theme: jekyll-theme-example

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

sidebars:
- lb2_sidebar
- lb3_sidebar
- lb4_sidebar
- contrib_sidebar
- community_sidebar
- es_lb2_sidebar
- fr_lb2_sidebar
- ja_lb2_sidebar
- ko_lb3_sidebar
- ko_lb2_sidebar
- ru_lb2_sidebar
- zh_lb2_sidebar
- pt-br_lb2_sidebar
